CFLAGS=-std=c11 -O3 -Wall -Wextra -Wpedantic -g

all: main
main: src/main.c src/calculations.c src/arithmetic_helper.c src/calculation_helper.c src/conversion.c
	$(CC) $(CFLAGS) -o $@ $^
clean:
	rm -f main