CFLAGS=-std=c11 -O3 -Wall -Wextra -Wpedantic -g

all: sub
sub: tests/subtraction_tests.c src/calculations.c src/arithmetic_helper.c src/calculation_helper.c
	$(CC) $(CFLAGS) -o $@ $^
clean:
	rm -f add